services:
  c1:
    build:
      dockerfile: docker/Dockerfile.c1
      context: .
    container_name: lab5-c1
    networks: [lab5-net]

  c2:
    build:
      dockerfile: docker/Dockerfile.c2
      context: .
    container_name: lab5-c2
    networks: [lab5-net]

  c3:
    build:
      dockerfile: docker/Dockerfile.c3
      context: .
    container_name: lab5-c3
    networks: [lab5-net]

  s1:
    build:
      dockerfile: docker/Dockerfile.c4
      context: .
    container_name: lab5-s1
    hostname: s1
    networks: [lab5-net]
    ports:
      - "2222:22"

networks:
  lab5-net:
    name: lab5-net

